#spring:
#  application:
#    name: concert
#
#  profiles:
#    default: local
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: hhplus2025
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 3
#      connection-timeout: 10000
#      max-lifetime: 60000

spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    database: mysql
    generate-ddl: true
    open-in-view: false
    show-sql: true